# Generated by Django 4.2 on 2023-06-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='model',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
