# Generated by Django 4.2 on 2023-06-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='model',
            new_name='total',
        ),
    ]
